### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by brucellino** [FutureGateway/APIServer#3]
Can we have a "CONTRIBUTING.md" file that tells us how to contribute ?

**Comment by fmarco76** [comment]
Would you have a CONTRIBUTING.md per project or something more generic for all the packages inside the organisation?

Nevertheless, I am not sure you are on the correct repository.

**Comment by brucellino** [comment]
something per project (ie repo). 

> Nevertheless, I am not sure you are on the correct repository.

Hey, it's in @FutureGateway - must be the right repo :wink:  if not, what _is_ the correct repo ?

**Comment by fmarco76** [comment]
In FutureGateway there are two API Service. Have a look at available packages

**Comment by brucellino** [comment]
Ok, so I was looking for https://github.com/FutureGateway/fgAPIServer - but it would still be nice to have some collaboration guides - maybe https://mozillascience.github.io/working-open-workshop/index.html#handouts can help.

**Comment by fmarco76** [comment]
I agree on the collaboration/contribution guideline. I will add something ASAP

**Comment by fmarco76** [comment]
Added
